name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    if: ${{ github.repository_owner == 'hugoschool' }}
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v6
      - name: Compiling program
        timeout-minutes: 2
        run: make -j`nproc`
      - name: Run tests
        run: python3 tests/babaorum.py
